FROM nginx:latest

# Switch to root user to install packages
USER root

RUN apt-get update && \
    apt-get install -y curl && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
    rm -rf /var/lib/apt/lists/

# Install Node.js LTS version using nvm
RUN /bin/bash -c "source /root/.nvm/nvm.sh && nvm install --lts"

WORKDIR /app

COPY . .

WORKDIR /app/website_example
RUN /bin/bash -c "source /root/.nvm/nvm.sh && npm install"

WORKDIR /app
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf


